version: '3'
services:
  nginx-service:
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php-service
      - mysql-service

  nginx-client:
    build: ./nginx-client/
    ports:
      - "9090:9090"
    volumes:
      - ./client/:/var/www/html/
      
  php-service:
    build: ./php/
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    depends_on:
      - mysql-service
  mysql-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"